// Auth
export const AUTH_START = "AUTH_START";

// Articles
export const GET_ALL_ARTICLES_SUCCESS = "GET_ALL_ARTICLES_SUCCESS";
export const GET_ALL_ARTICLES_ERROR = "GET_ALL_ARTICLES_ERROR";
export const POST_NEW_ARTICLE_ERROR = "POST_NEW_ARTICLE_ERROR";
export const POST_NEW_ARTICLE_SUCCESS = "POST_NEW_ARTICLE_SUCCESS";